### PR TITLE
cakephp fashioned redirect if possible

### PR DESCRIPTION
**Pull request by cap5lut**
Sorry that I am bothering you again.

Due some debugging in my cakephp project I realized how the redirecting of this plugin works and that its levering out the cakephp's redirect. So I thought of adding that.

Basically it will just check if there is a `redirect` method in the controller and passes the redirect attribute to it, because in the cakephp's way to pass the redirection data (for example as `array("controller" => "tests", "action" => "index")`) I changed the initialization of `$this->redirect` and the comparison in the `redirectIfIsSet` method as well.

If the `redirect` method does not exist it will still use the old way.

### CODE REVIEW

**Comment by AlessandroMinoccheri** [comment]
Thanks for your contribute!

Can you please add one or more tests for this?

**Comment by cap5lut** [comment]
Oh right, I always forget to add tests, sorry, will do it in ~1h

**Comment by AlessandroMinoccheri** [comment]
No problem, when you can.

It's important to add test when you add a feature to demonstrate that your code works fine, It's not a very used plugin but tests guarantee that this plugin works fine if someone would like to use It.

Thanks for your contribute

**Comment by cap5lut** [comment]
Some unexpected stuff occured, so its delayed, and I have a question: for the test i basically need another class, so where should I put it? (Basically its just a class that implements redirect, to check afterwards if its redirect method gets called)

**Comment by AlessandroMinoccheri** [comment]
You can a directory into test like "Resources" and put there a class for example

**Comment by cap5lut** [comment]
Something is still wrong with the namespacing for the MockRedirect class, can you help me there?

I've put the class into the file `/tests/TestCase/Resources/MockRedirect.php`
The namespace is `App\Test\TestCase\Resources`
The test itself uses `use App\Test\TestCase\Resources\MockRedirect;`

But it still won't load the class ending up in an class not found error.

**Comment by AlessandroMinoccheri** [comment]
Can you show me the error?

Try to launch the command:

`composer dump-autoload`

**Comment by cap5lut** [comment]
well as Scrutinizer check says:
```
There was 1 error:

1) App\Test\TestCase\Controller\Component\UserPermissionComponentTest::testCakePhpFashionedRedirect
Error: Class 'App\Test\TestCase\Resources\MockRedirect' not found

/home/scrutinizer/build/tests/TestCase/Controller/Component/UserPermissionComponentTest.php:235
```

Do I have to run `composer dump-autoload` in the CakePHP root directory or in the plugin root directory?

**Comment by AlessandroMinoccheri** [comment]
Try to change autoload into composer.json into this:

```
"autoload": {
      "psr-4": {
          "UserPermissions\\": "src",
          "Tests\\":"tests"
      }
  }
```

And after launch composer dump-autoload into the root of the project and into the root of the plugin please

**Comment by cap5lut** [comment]
It's still showing the same error.

**Comment by AlessandroMinoccheri** [comment]
If you can't include into Resources directory, try to put the class into the same directory of the test file please @cap5lut

**Comment by AlessandroMinoccheri** [comment]
Any news on this PR? @cap5lut

**Comment by AlessandroMinoccheri** [comment]
I am closing this PR because it passed a lot of time :)

**Pull request closed without merging**
